/*
  One book, shared by Home, Bookings and the Calendar.

  Dates are real ISO days and every weekday label is derived from them, so the
  three screens cannot drift apart and the month grid lands on the right squares.
  Formatting is done with fixed arrays rather than toLocaleDateString: the output
  is then identical on the server and in the browser, whatever the locale or
  timezone, which keeps hydration quiet.
*/

const WEEKDAY_SHORT = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const WEEKDAY_LONG = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
const MONTH_LONG = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

// Midday keeps the calendar day stable no matter which side of UTC you are on.
export const at = (iso) => new Date(`${iso}T12:00:00`);
export const dayLabel = (iso) => {
  const d = at(iso);
  return `${WEEKDAY_SHORT[d.getDay()]} ${d.getDate()}`;
};
export const dateLabel = (iso) => {
  const d = at(iso);
  return `${WEEKDAY_LONG[d.getDay()]} ${d.getDate()} ${MONTH_LONG[d.getMonth()]}`;
};
export const monthLabel = (year, month) => `${MONTH_LONG[month]} ${year}`;
export { WEEKDAY_SHORT, WEEKDAY_LONG, MONTH_LONG };

export const STATUS = {
  confirmed: { label: "Confirmed", group: "upcoming", tone: "brand" },
  option: { label: "On option", group: "options", tone: "muted" },
  hold: { label: "Pencilled", group: "options", tone: "muted" },
  completed: { label: "Completed", group: "past", tone: "muted" },
  released: { label: "Released", group: "past", tone: "muted" },
  cancelled: { label: "Cancelled", group: "past", tone: "muted" },
};

export const GROUPS = [
  { id: "upcoming", label: "Upcoming" },
  { id: "options", label: "Options" },
  { id: "past", label: "Past" },
];

export const BOOKINGS = [
  {
    id: "bottega",
    on: "2026-03-10",
    client: "Bottega Veneta",
    title: "FW26 fitting — full look review",
    kind: "Fitting",
    status: "confirmed",
    call: "09:00",
    wrap: "13:00 est.",
    city: "London",
    venue: "180 The Strand",
    address: "180 Strand, WC2R 1EA",
    fee: "$3,200",
    feeNote: "Day rate · 20% commission",
    usage: "Fitting only — no usage",
    agent: "Nadia Okonkwo",
    bring: ["Black heels", "Seamless nude slip", "Clean face, no lash extensions"],
    schedule: [
      ["09:00", "Call — studio 2, ask for Marta"],
      ["09:15", "Hair and makeup"],
      ["10:00", "First look on the stand"],
      ["12:00", "Coat re-cut, expect pins"],
      ["13:00", "Wrap"],
    ],
    note: "Second fitting. They are cutting the coat down a full size, so expect pins.",
  },
  {
    id: "mulberry",
    on: "2026-03-11",
    client: "Mulberry",
    title: "SS27 accessories — studio day",
    kind: "E-comm",
    status: "confirmed",
    call: "08:30",
    wrap: "15:00 est.",
    city: "London",
    venue: "Bermondsey Studios",
    address: "12 Tanner St, SE1 3LE",
    fee: "$2,600",
    feeNote: "Day rate · 20% commission",
    usage: "E-comm + social · 12 months · worldwide",
    agent: "Tunde Bakare",
    bring: ["Nude seamless set", "Own flats", "Nails bare"],
    schedule: [
      ["08:30", "Call"],
      ["09:00", "Hair and makeup"],
      ["10:00", "Bags, first block"],
      ["13:00", "Small leather goods"],
      ["15:00", "Wrap — Eurostar at 19:04"],
    ],
    note: "Tight turnaround. You are on the Eurostar to Paris the same evening.",
  },
  {
    id: "acne",
    travelOn: "2026-03-11",
    on: "2026-03-12",
    client: "Acne Studios",
    title: "FW26 campaign — studio and street",
    kind: "Campaign",
    status: "confirmed",
    call: "07:30",
    wrap: "18:00 est.",
    city: "Paris",
    venue: "Studio Ekko",
    address: "12 Rue de Cléry, 75002",
    fee: "$12,000",
    feeNote: "Day rate + usage · 20% commission",
    usage: "Digital + OOH · 12 months · EU",
    agent: "Elise Moreau",
    travel: "Eurostar Wed 11, 19:04 · Hôtel Le Marais, keys at desk",
    bring: ["Passport", "Own nude underwear", "No jewellery"],
    schedule: [
      ["06:45", "Car from the hotel"],
      ["07:30", "Call — Studio Ekko"],
      ["08:15", "Hair and makeup"],
      ["10:00", "Studio setup, six looks"],
      ["14:00", "Street setup, Rue de Cléry"],
      ["18:00", "Wrap"],
    ],
    note: "Biggest booking of the season. Two setups, and the usage alone is most of the fee.",
  },
  {
    id: "selfridges",
    on: "2026-03-16",
    client: "Selfridges",
    title: "E-comm fittings — SS27 intake",
    kind: "E-comm",
    status: "confirmed",
    call: "08:00",
    wrap: "16:00 est.",
    city: "London",
    venue: "Selfridges Studio",
    address: "400 Oxford St, W1A 1AB",
    fee: "$1,900",
    feeNote: "Half day · 20% commission",
    usage: "E-comm · 24 months · worldwide",
    agent: "Tunde Bakare",
    bring: ["Nude seamless set", "Hair down, no product"],
    schedule: [
      ["08:00", "Call — goods entrance, Duke St"],
      ["08:30", "Hair and makeup"],
      ["09:15", "First block, 30 looks"],
      ["12:30", "Break"],
      ["16:00", "Wrap"],
    ],
    note: "High volume day — 60+ looks. Bring something to eat between blocks.",
  },
  {
    id: "loewe",
    travelOn: "2026-03-16",
    on: "2026-03-17",
    client: "Loewe",
    title: "Casting — FW26 campaign",
    kind: "Casting",
    status: "option",
    optionRank: "Casting request",
    expires: "Reel due 18:00",
    call: "14:00",
    wrap: "15:00 est.",
    city: "Paris",
    venue: "Casting suite, Rue Saint-Honoré",
    address: "231 Rue Saint-Honoré, 75001",
    fee: "—",
    feeNote: "Unpaid casting",
    usage: "None",
    agent: "Elise Moreau",
    travel: "Eurostar Mon 16, 20:01",
    bring: ["Digitals", "Heels", "Hair down"],
    schedule: [
      ["14:00", "Call"],
      ["14:15", "Polaroids"],
      ["14:30", "Walk"],
      ["15:00", "Out"],
    ],
    note: "The casting director asked for your reel by name after the Acne shoot.",
  },
  {
    id: "tilbury",
    on: "2026-03-19",
    client: "Charlotte Tilbury",
    title: "Beauty — complexion launch",
    kind: "Beauty",
    status: "confirmed",
    call: "07:00",
    wrap: "17:00 est.",
    city: "London",
    venue: "Spring Studios",
    address: "6 Blossom St, E1 6BX",
    fee: "$5,400",
    feeNote: "Day rate + usage · 20% commission",
    usage: "Digital + in-store · 18 months · worldwide",
    agent: "Nadia Okonkwo",
    bring: ["Bare skin — no products for 24h", "Hair washed, unstyled"],
    schedule: [
      ["07:00", "Call"],
      ["07:30", "Skin prep, two hours"],
      ["10:00", "Close-up beauty"],
      ["14:00", "Product in hand"],
      ["17:00", "Wrap"],
    ],
    note: "Skin-first booking. Nothing on your face the day before, not even SPF they have not approved.",
  },
  {
    id: "vogue",
    travelOn: "2026-03-19",
    on: "2026-03-20",
    client: "Vogue Scandinavia",
    title: "Editorial — eight pages, spring issue",
    kind: "Editorial",
    status: "option",
    optionRank: "First option",
    expires: "Expires Wednesday",
    call: "08:30",
    wrap: "19:00 est.",
    city: "Copenhagen",
    venue: "Nordhavn warehouse",
    address: "Sundkaj 9, 2150",
    fee: "$6,500",
    feeNote: "Editorial rate · flights and hotel covered",
    usage: "Print + digital · 6 months · Nordics",
    agent: "Nadia Okonkwo",
    travel: "SAS Thu 19, 20:15 · hotel covered",
    bring: ["Passport", "Portfolio"],
    schedule: [
      ["08:30", "Call"],
      ["09:00", "Hair and makeup"],
      ["10:30", "Story one, four looks"],
      ["14:00", "Story two, four looks"],
      ["19:00", "Wrap"],
    ],
    note: "Eight pages is a lot of book for a new face. Nadia wants this one.",
  },
  {
    id: "burberry",
    on: "2026-03-23",
    client: "Burberry",
    title: "Campaign — outerwear, two looks",
    kind: "Campaign",
    status: "confirmed",
    call: "06:30",
    wrap: "16:00 est.",
    city: "London",
    venue: "Hackney Wick location",
    address: "Queens Yard, E9 5EN",
    fee: "$7,500",
    feeNote: "Day rate + usage · 20% commission",
    usage: "Digital + OOH · 12 months · UK and EU",
    agent: "Nadia Okonkwo",
    bring: ["Thermals", "Own boots", "Clean face"],
    schedule: [
      ["06:30", "Call — first light"],
      ["07:00", "Hair and makeup in the van"],
      ["08:00", "Look one, exterior"],
      ["12:00", "Move to interior"],
      ["16:00", "Wrap"],
    ],
    note: "Outdoor in March. Layer up under the coats — there is no warm holding area.",
  },
  {
    id: "jacquemus",
    travelOn: "2026-03-24",
    on: "2026-03-25",
    client: "Jacquemus",
    title: "Lookbook — resort capsule",
    kind: "Lookbook",
    status: "confirmed",
    call: "10:00",
    wrap: "17:00 est.",
    city: "Paris",
    venue: "Le Marais rooftop",
    address: "3 Rue de Turenne, 75004",
    fee: "$4,800",
    feeNote: "Day rate · 20% commission",
    usage: "Lookbook + social · 12 months · worldwide",
    agent: "Elise Moreau",
    travel: "Eurostar Tue 24, 18:01 · Hôtel Le Marais",
    bring: ["Flat sandals", "Minimal tan lines"],
    schedule: [
      ["10:00", "Call"],
      ["10:30", "Hair and makeup"],
      ["11:30", "Rooftop, natural light"],
      ["15:00", "Second setup, stairwell"],
      ["17:00", "Wrap"],
    ],
    note: "Outdoor shoot. Weather call goes out the evening before.",
  },
  {
    id: "cos",
    on: "2026-03-26",
    client: "COS",
    title: "SS27 e-comm — two day block",
    kind: "E-comm",
    status: "hold",
    optionRank: "Agency pencil",
    call: "08:00",
    wrap: "17:00 est.",
    city: "London",
    venue: "Hoxton Studios",
    address: "Unit 4, Vyner St, E2 9DG",
    fee: "$2,200",
    feeNote: "Per day · 20% commission",
    usage: "E-comm · 24 months · worldwide",
    agent: "Tunde Bakare",
    bring: ["Nude seamless set", "Flat shoes"],
    schedule: [
      ["08:00", "Call"],
      ["08:30", "Hair and makeup"],
      ["09:00", "First block"],
      ["17:00", "Wrap"],
    ],
    note: "Held across two days, and the second one collides with the Prada option on the 27th.",
  },
  {
    id: "prada",
    on: "2026-03-27",
    client: "Prada",
    title: "FW26 runway — fitting then show",
    kind: "Runway",
    status: "option",
    optionRank: "Second option",
    call: "07:15",
    wrap: "Late",
    city: "London",
    venue: "180 The Strand",
    address: "180 Strand, WC2R 1EA",
    fee: "$9,000",
    feeNote: "Show rate · 20% commission",
    usage: "Show footage · perpetual · worldwide",
    agent: "Nadia Okonkwo",
    bring: ["Black heels", "Clean face, no lashes"],
    schedule: [
      ["07:15", "Call — car at 06:30"],
      ["08:00", "Fitting"],
      ["12:00", "Line-up"],
      ["17:00", "Show"],
      ["Late", "Wrap"],
    ],
    note: "Second option behind a Milan girl. The casting director has already seen the reel.",
  },
  {
    id: "ganniss",
    on: "2026-03-28",
    client: "Ganni",
    title: "Campaign — SS27 denim",
    kind: "Campaign",
    status: "option",
    optionRank: "Second option",
    call: "09:00",
    wrap: "18:00 est.",
    city: "Copenhagen",
    venue: "Islands Brygge",
    address: "Njalsgade 21, 2300",
    fee: "$5,900",
    feeNote: "Day rate + usage · 20% commission",
    usage: "Digital + OOH · 12 months · EU",
    agent: "Nadia Okonkwo",
    travel: "Flights and hotel covered",
    bring: ["Passport", "Nude seamless set"],
    schedule: [
      ["09:00", "Call"],
      ["09:30", "Hair and makeup"],
      ["11:00", "Denim, first block"],
      ["18:00", "Wrap"],
    ],
    note: "Repeat client — they still owe on the February campaign. Worth confirming anyway.",
  },
  {
    id: "arket",
    travelOn: "2026-03-29",
    on: "2026-03-30",
    client: "Arket",
    title: "SS27 e-comm — two day block",
    kind: "E-comm",
    status: "confirmed",
    call: "08:00",
    wrap: "17:00 est.",
    city: "Stockholm",
    venue: "Studio Södermalm",
    address: "Hornsgatan 89, 118 49",
    fee: "$2,100",
    feeNote: "Per day · 20% commission",
    usage: "E-comm · 24 months · worldwide",
    agent: "Tunde Bakare",
    travel: "SAS to Stockholm Sun 29 · agency covered",
    bring: ["Nude seamless set", "Flat shoes"],
    schedule: [
      ["08:00", "Call"],
      ["08:30", "Hair and makeup"],
      ["09:15", "Day one, 40 looks"],
      ["17:00", "Wrap"],
    ],
    note: "Two consecutive days. Day two is the same call time at the same studio.",
  },
  {
    id: "zara",
    on: "2026-02-27",
    client: "Zara",
    title: "SS26 lookbook",
    kind: "Lookbook",
    status: "completed",
    paid: true,
    call: "09:00",
    wrap: "16:30",
    city: "London",
    venue: "Shoreditch Studios",
    address: "37 Rivington St, EC2A 3QQ",
    fee: "$2,400",
    feeNote: "Cleared 4 March",
    usage: "Lookbook · 12 months · worldwide",
    agent: "Tunde Bakare",
    bring: [],
    schedule: [],
    note: "Wrapped two hours early. The client asked for you again in the autumn.",
  },
  {
    id: "voguebeauty",
    on: "2026-02-19",
    client: "Vogue Scandinavia",
    title: "Beauty story — six pages",
    kind: "Editorial",
    status: "completed",
    paid: true,
    call: "07:00",
    wrap: "18:00",
    city: "Copenhagen",
    venue: "Studio Nord",
    address: "Refshalevej 163A, 1432",
    fee: "$8,400",
    feeNote: "Cleared 2 March",
    usage: "Print + digital · 6 months · Nordics",
    agent: "Nadia Okonkwo",
    bring: [],
    schedule: [],
    note: "First cover-adjacent booking. The tear sheets are already in your portfolio.",
  },
  {
    id: "ganni",
    on: "2026-02-10",
    client: "Ganni",
    title: "Campaign — denim capsule",
    kind: "Campaign",
    status: "completed",
    paid: false,
    call: "08:30",
    wrap: "17:00",
    city: "Copenhagen",
    venue: "Islands Brygge",
    address: "Njalsgade 21, 2300",
    fee: "$5,600",
    feeNote: "Invoiced 12 Feb · 30 day terms",
    usage: "Digital + OOH · 12 months · EU",
    agent: "Nadia Okonkwo",
    bring: [],
    schedule: [],
    note: "Payment is nine days past terms. Accounts have been chased twice.",
  },
  {
    id: "toteme",
    on: "2026-02-05",
    client: "Totême",
    title: "E-comm — knitwear drop",
    kind: "E-comm",
    status: "cancelled",
    call: "09:00",
    wrap: "—",
    city: "Stockholm",
    venue: "Studio Vasastan",
    address: "Odengatan 42, 113 51",
    fee: "$1,800",
    feeNote: "Cancelled inside 48h · 50% fee due",
    usage: "None",
    agent: "Tunde Bakare",
    bring: [],
    schedule: [],
    note: "The client pushed the drop. Half the fee is owed under the cancellation window.",
  },
];
