// Mock data for the Candor talent management dashboard

export const talent = [
  {
    id: "1",
    name: "Ayotomiwa Durojaye",
    stageName: "Zara",
    gender: "Female",
    age: 22,
    height: "175 cm / 5'9\"",
    board: "Main Board",
    status: "Active",
    onboardingStep: 8,
    talent: "Model",
    category: "Fashion",
    nationality: "Nigerian",
    location: "Lagos",
    joinDate: "2025-06-15",
    bookings: 12,
    avatar: "AD",
    email: "zara@candoragency.com",
    phone: "+234 801 234 5678",
    instagram: "@zara.models",
    contractType: "Exclusive",
    contractStart: "2025-06-15",
    contractEnd: "2026-06-15",
    commissionRate: 20,
    isPublic: true,
    measurements: {
      bust: "82 cm",
      waist: "60 cm",
      hips: "88 cm",
      shoeSize: "39 EU",
      hairColor: "Black",
      eyeColor: "Brown",
    },
    portfolioStatus: {
      compCard: "Current",
      digitals: "Current",
      imageCount: 24,
      lastTestShoot: "2026-01-15",
      nextScheduledShoot: "2026-04-01",
    },
  },
  {
    id: "2",
    name: "John Smith",
    stageName: "Phoenix",
    gender: "Male",
    age: 25,
    height: "178 cm / 5'10\"",
    board: "Main Board",
    status: "Active",
    onboardingStep: 8,
    talent: "Model",
    category: "Commercial",
    nationality: "Nigerian",
    location: "Lagos",
    joinDate: "2025-04-20",
    bookings: 8,
    avatar: "JS",
    email: "phoenix@candoragency.com",
    phone: "+234 802 345 6789",
    instagram: "@phoenix.models",
    contractType: "Exclusive",
    contractStart: "2025-04-20",
    contractEnd: "2026-04-20",
    commissionRate: 20,
    isPublic: true,
    measurements: {
      chest: "96 cm",
      waist: "78 cm",
      hips: "92 cm",
      shoeSize: "43 EU",
      hairColor: "Black",
      eyeColor: "Dark Brown",
    },
    portfolioStatus: {
      compCard: "Current",
      digitals: "Needs Update",
      imageCount: 18,
      lastTestShoot: "2025-11-20",
      nextScheduledShoot: null,
    },
  },
  {
    id: "3",
    name: "Chioma Nwosu",
    stageName: "Atlas",
    gender: "Female",
    age: 23,
    height: "180 cm / 5'11\"",
    board: "Main Board",
    status: "Active",
    onboardingStep: 8,
    talent: "Model",
    category: "Fashion",
    nationality: "Nigerian",
    location: "Lagos",
    joinDate: "2025-05-10",
    bookings: 15,
    avatar: "CN",
    email: "atlas@candoragency.com",
    phone: "+234 803 456 7890",
    instagram: "@atlas.models",
    contractType: "Exclusive",
    contractStart: "2025-05-10",
    contractEnd: "2026-05-10",
    commissionRate: 20,
    isPublic: true,
    measurements: {
      bust: "84 cm",
      waist: "62 cm",
      hips: "90 cm",
      shoeSize: "40 EU",
      hairColor: "Black",
      eyeColor: "Brown",
    },
    portfolioStatus: {
      compCard: "Current",
      digitals: "Current",
      imageCount: 32,
      lastTestShoot: "2026-02-10",
      nextScheduledShoot: "2026-04-15",
    },
  },
  {
    id: "4",
    name: "Emeka Okafor",
    stageName: "Blaze",
    gender: "Male",
    age: 27,
    height: "185 cm / 6'1\"",
    board: "New Faces",
    status: "Onboarding",
    onboardingStep: 5,
    talent: "Model",
    category: "Fashion",
    nationality: "Nigerian",
    location: "Lagos",
    joinDate: "2026-02-28",
    bookings: 0,
    avatar: "EO",
    email: "blaze@candoragency.com",
    phone: "+234 804 567 8901",
    instagram: "@blaze.official",
    contractType: "Non-Exclusive",
    contractStart: "2026-02-28",
    contractEnd: "2027-02-28",
    commissionRate: 20,
    isPublic: false,
    measurements: {
      chest: "100 cm",
      waist: "80 cm",
      hips: "94 cm",
      shoeSize: "44 EU",
      hairColor: "Black",
      eyeColor: "Brown",
    },
    portfolioStatus: {
      compCard: "Pending",
      digitals: "Pending",
      imageCount: 0,
      lastTestShoot: null,
      nextScheduledShoot: "2026-04-05",
    },
  },
  {
    id: "5",
    name: "Adaeze Ikenna",
    stageName: "Velvet",
    gender: "Female",
    age: 21,
    height: "172 cm / 5'8\"",
    board: "New Faces",
    status: "Onboarding",
    onboardingStep: 3,
    talent: "Model",
    category: "Commercial",
    nationality: "Nigerian",
    location: "Lagos",
    joinDate: "2026-03-10",
    bookings: 0,
    avatar: "AI",
    email: "velvet@candoragency.com",
    phone: "+234 805 678 9012",
    instagram: "@velvet.ng",
    contractType: "Non-Exclusive",
    contractStart: "2026-03-10",
    contractEnd: "2027-03-10",
    commissionRate: 20,
    isPublic: false,
    measurements: {
      bust: "80 cm",
      waist: "58 cm",
      hips: "86 cm",
      shoeSize: "38 EU",
      hairColor: "Dark Brown",
      eyeColor: "Brown",
    },
    portfolioStatus: {
      compCard: "Pending",
      digitals: "Pending",
      imageCount: 0,
      lastTestShoot: null,
      nextScheduledShoot: null,
    },
  },
  {
    id: "6",
    name: "Tunde Abiola",
    stageName: "Storm",
    gender: "Male",
    age: 24,
    height: "182 cm / 6'0\"",
    board: "Main Board",
    status: "Active",
    onboardingStep: 8,
    talent: "Model",
    category: "Commercial",
    nationality: "Nigerian",
    location: "Lagos",
    joinDate: "2025-08-01",
    bookings: 6,
    avatar: "TA",
    email: "storm@candoragency.com",
    phone: "+234 806 789 0123",
    instagram: "@storm.lagos",
    contractType: "Exclusive",
    contractStart: "2025-08-01",
    contractEnd: "2026-08-01",
    commissionRate: 20,
    isPublic: true,
    measurements: {
      chest: "98 cm",
      waist: "76 cm",
      hips: "90 cm",
      shoeSize: "43 EU",
      hairColor: "Black",
      eyeColor: "Dark Brown",
    },
    portfolioStatus: {
      compCard: "Current",
      digitals: "Current",
      imageCount: 16,
      lastTestShoot: "2025-12-05",
      nextScheduledShoot: null,
    },
  },
  {
    id: "7",
    name: "Ngozi Eze",
    stageName: "Muse",
    gender: "Female",
    age: 20,
    height: "176 cm / 5'9\"",
    board: "Main Board",
    status: "Inactive",
    onboardingStep: 8,
    talent: "Model",
    category: "Editorial",
    nationality: "Nigerian",
    location: "London",
    joinDate: "2025-01-15",
    bookings: 3,
    avatar: "NE",
    email: "muse@candoragency.com",
    phone: "+44 7911 123456",
    instagram: "@muse.london",
    contractType: "Non-Exclusive",
    contractStart: "2025-01-15",
    contractEnd: "2026-01-15",
    commissionRate: 15,
    isPublic: false,
    measurements: {
      bust: "81 cm",
      waist: "59 cm",
      hips: "87 cm",
      shoeSize: "39 EU",
      hairColor: "Black",
      eyeColor: "Hazel",
    },
    portfolioStatus: {
      compCard: "Outdated",
      digitals: "Outdated",
      imageCount: 8,
      lastTestShoot: "2025-06-20",
      nextScheduledShoot: null,
    },
  },
];

export const clients = [
  {
    id: "c1",
    name: "Lagos Fashion Week",
    contactPerson: "Mrs. Folake Coker",
    email: "bookings@lagosfashionweek.ng",
    phone: "+234 901 234 5678",
    type: "Fashion Event",
    clientType: "Established",
    paymentTerms: "Net 14",
    status: "Active",
    totalBookings: 8,
    outstanding: "NGN 2,400,000",
    joinDate: "2025-03-01",
  },
  {
    id: "c2",
    name: "GTBank",
    contactPerson: "Mr. Ade Williams",
    email: "marketing@gtbank.com",
    phone: "+234 902 345 6789",
    type: "Corporate",
    clientType: "Established",
    paymentTerms: "Net 14",
    status: "Active",
    totalBookings: 3,
    outstanding: "NGN 0",
    joinDate: "2025-06-15",
  },
  {
    id: "c3",
    name: "Ziva Lagos",
    contactPerson: "Nneka Obi",
    email: "creative@zivalagos.com",
    phone: "+234 903 456 7890",
    type: "Fashion Brand",
    clientType: "Established",
    paymentTerms: "Net 14",
    status: "Active",
    totalBookings: 5,
    outstanding: "NGN 750,000",
    joinDate: "2025-09-20",
  },
  {
    id: "c4",
    name: "Pepsi Nigeria",
    contactPerson: "Chidi Nnamdi",
    email: "agency@pepsi.ng",
    phone: "+234 904 567 8901",
    type: "FMCG",
    clientType: "New",
    paymentTerms: "100% Upfront",
    status: "Pending",
    totalBookings: 0,
    outstanding: "NGN 0",
    joinDate: "2026-03-01",
  },
  {
    id: "c5",
    name: "Vogue Afrique",
    contactPerson: "Amara Diop",
    email: "casting@voguefr.com",
    phone: "+33 6 12 34 56 78",
    type: "Editorial",
    clientType: "Established",
    paymentTerms: "Net 14",
    status: "Active",
    totalBookings: 4,
    outstanding: "NGN 1,200,000",
    joinDate: "2025-11-10",
  },
];

export const bookings = [
  {
    id: "b1",
    client: "Lagos Fashion Week",
    clientId: "c1",
    talent: "Zara, Atlas, Storm",
    talentIds: ["1", "3", "6"],
    type: "Runway",
    date: "2026-04-12",
    endDate: "2026-04-13",
    status: "Confirmed",
    value: "NGN 1,800,000",
    currency: "NGN",
    mediaUsage: "Social media, press",
    territory: "West Africa",
    usageTerm: "6 months",
    dealMemo: true,
    milestoneOptIn: true,
    createdAt: "2026-03-01",
  },
  {
    id: "b2",
    client: "Ziva Lagos",
    clientId: "c3",
    talent: "Zara",
    talentIds: ["1"],
    type: "Editorial",
    date: "2026-03-28",
    endDate: "2026-03-28",
    status: "In Progress",
    value: "NGN 450,000",
    currency: "NGN",
    mediaUsage: "Print, digital",
    territory: "Africa",
    usageTerm: "12 months",
    dealMemo: true,
    milestoneOptIn: false,
    createdAt: "2026-02-15",
  },
  {
    id: "b3",
    client: "GTBank",
    clientId: "c2",
    talent: "Phoenix, Atlas",
    talentIds: ["2", "3"],
    type: "Commercial",
    date: "2026-04-05",
    endDate: "2026-04-06",
    status: "Confirmed",
    value: "NGN 1,200,000",
    currency: "NGN",
    mediaUsage: "TV, digital, OOH",
    territory: "Nigeria",
    usageTerm: "12 months",
    dealMemo: true,
    milestoneOptIn: true,
    createdAt: "2026-03-10",
  },
  {
    id: "b4",
    client: "Vogue Afrique",
    clientId: "c5",
    talent: "Atlas, Muse",
    talentIds: ["3", "7"],
    type: "Editorial",
    date: "2026-04-20",
    endDate: "2026-04-21",
    status: "Pending",
    value: "NGN 900,000",
    currency: "NGN",
    mediaUsage: "Print",
    territory: "Global",
    usageTerm: "Perpetual",
    dealMemo: false,
    milestoneOptIn: false,
    createdAt: "2026-03-15",
  },
  {
    id: "b5",
    client: "Pepsi Nigeria",
    clientId: "c4",
    talent: "Phoenix",
    talentIds: ["2"],
    type: "TVC",
    date: "2026-05-01",
    endDate: "2026-05-03",
    status: "Pending",
    value: "NGN 2,000,000",
    currency: "NGN",
    mediaUsage: "TV, digital, social",
    territory: "West Africa",
    usageTerm: "24 months",
    dealMemo: false,
    milestoneOptIn: false,
    createdAt: "2026-03-18",
  },
  {
    id: "b6",
    client: "Lagos Fashion Week",
    clientId: "c1",
    talent: "Velvet",
    talentIds: ["5"],
    type: "Runway",
    date: "2026-04-12",
    endDate: "2026-04-12",
    status: "Casting",
    value: "NGN 350,000",
    currency: "NGN",
    mediaUsage: "Social media",
    territory: "Nigeria",
    usageTerm: "3 months",
    dealMemo: false,
    milestoneOptIn: false,
    createdAt: "2026-03-20",
  },
];

export const invoices = [
  {
    id: "INV-001",
    client: "Lagos Fashion Week",
    booking: "b1",
    amount: "NGN 1,800,000",
    commission: "NGN 360,000",
    talentPay: "NGN 1,440,000",
    status: "Paid",
    issuedDate: "2026-03-01",
    dueDate: "2026-03-15",
  },
  {
    id: "INV-002",
    client: "Ziva Lagos",
    booking: "b2",
    amount: "NGN 450,000",
    commission: "NGN 90,000",
    talentPay: "NGN 360,000",
    status: "Overdue",
    issuedDate: "2026-02-20",
    dueDate: "2026-03-06",
  },
  {
    id: "INV-003",
    client: "GTBank",
    booking: "b3",
    amount: "NGN 1,200,000",
    commission: "NGN 240,000",
    talentPay: "NGN 960,000",
    status: "Sent",
    issuedDate: "2026-03-18",
    dueDate: "2026-04-01",
  },
  {
    id: "INV-004",
    client: "Vogue Afrique",
    booking: "b4",
    amount: "NGN 900,000",
    commission: "NGN 180,000",
    talentPay: "NGN 720,000",
    status: "Draft",
    issuedDate: "",
    dueDate: "",
  },
];

export const notifications = [
  {
    id: "n1",
    type: "availability_check",
    title: "Availability Check - Vogue Afrique",
    body: "Are you available for an editorial shoot on April 20-21, 2026? Location: Lagos studio.",
    recipientIds: ["3", "7"],
    recipientNames: ["Atlas", "Muse"],
    sentBy: "Candor Admin",
    sentAt: "2026-03-20T10:30:00",
    responses: [
      { talentId: "3", talentName: "Atlas", response: "Available", respondedAt: "2026-03-20T11:15:00" },
    ],
    escalated: true,
  },
  {
    id: "n2",
    type: "booking_update",
    title: "Booking Confirmed - Lagos Fashion Week",
    body: "Your booking for Lagos Fashion Week runway show has been confirmed. Date: April 12-13, 2026. Call time: 7:00 AM.",
    recipientIds: ["1", "3", "6"],
    recipientNames: ["Zara", "Atlas", "Storm"],
    sentBy: "Candor Admin",
    sentAt: "2026-03-18T14:00:00",
    responses: [
      { talentId: "1", talentName: "Zara", response: "Accepted", respondedAt: "2026-03-18T14:30:00" },
      { talentId: "3", talentName: "Atlas", response: "Accepted", respondedAt: "2026-03-18T15:00:00" },
      { talentId: "6", talentName: "Storm", response: "Accepted", respondedAt: "2026-03-18T16:45:00" },
    ],
    escalated: false,
  },
  {
    id: "n3",
    type: "payment_update",
    title: "Payment Received - Lagos Fashion Week",
    body: "Payment of NGN 1,440,000 has been processed for Lagos Fashion Week runway booking. Please check your account.",
    recipientIds: ["1", "3", "6"],
    recipientNames: ["Zara", "Atlas", "Storm"],
    sentBy: "Candor Admin",
    sentAt: "2026-03-15T09:00:00",
    responses: [],
    escalated: false,
  },
  {
    id: "n4",
    type: "portfolio_request",
    title: "Portfolio Update Required",
    body: "Please submit updated digitals by March 30, 2026. We need front, side, and back shots in natural light.",
    recipientIds: ["2"],
    recipientNames: ["Phoenix"],
    sentBy: "Candor Admin",
    sentAt: "2026-03-22T11:00:00",
    responses: [],
    escalated: false,
  },
  {
    id: "n5",
    type: "pre_job_brief",
    title: "Pre-Job Brief - Ziva Lagos Editorial",
    body: "Attached is the brief for the Ziva Lagos editorial shoot on March 28. Mood: minimal luxury. Please arrive at 8:00 AM at Eko Hotel studio.",
    recipientIds: ["1"],
    recipientNames: ["Zara"],
    sentBy: "Candor Admin",
    sentAt: "2026-03-25T16:00:00",
    responses: [
      { talentId: "1", talentName: "Zara", response: "Acknowledged", respondedAt: "2026-03-25T17:20:00" },
    ],
    escalated: false,
  },
  {
    id: "n6",
    type: "general",
    title: "Agency Update - Easter Schedule",
    body: "The office will be closed April 18-21 for Easter. For urgent matters, please contact us via WhatsApp.",
    recipientIds: ["1", "2", "3", "6", "7"],
    recipientNames: ["Zara", "Phoenix", "Atlas", "Storm", "Muse"],
    sentBy: "Candor Admin",
    sentAt: "2026-03-14T10:00:00",
    responses: [],
    escalated: false,
  },
  {
    id: "n7",
    type: "availability_check",
    title: "Availability Check - GTBank Commercial",
    body: "GTBank is looking for talent for an annual report shoot. Dates: April 5-6, 2026. Are you available?",
    recipientIds: ["2", "3", "6"],
    recipientNames: ["Phoenix", "Atlas", "Storm"],
    sentBy: "Candor Admin",
    sentAt: "2026-03-08T09:00:00",
    responses: [
      { talentId: "2", talentName: "Phoenix", response: "Available", respondedAt: "2026-03-08T09:45:00" },
      { talentId: "3", talentName: "Atlas", response: "Available", respondedAt: "2026-03-08T10:20:00" },
      { talentId: "6", talentName: "Storm", response: "Not available", respondedAt: "2026-03-08T12:00:00" },
    ],
    escalated: false,
  },
];

export const documents = [
  {
    id: "d1",
    title: "Talent Agreement - Zara",
    type: "Agreement",
    talentId: "1",
    talentName: "Zara",
    fileName: "agreement_zara_2025.pdf",
    uploadedAt: "2025-06-15",
    dateSigned: "2025-06-15",
    bookingId: null,
    isPersonalised: true,
  },
  {
    id: "d2",
    title: "Talent Agreement - Phoenix",
    type: "Agreement",
    talentId: "2",
    talentName: "Phoenix",
    fileName: "agreement_phoenix_2025.pdf",
    uploadedAt: "2025-04-20",
    dateSigned: "2025-04-20",
    bookingId: null,
    isPersonalised: true,
  },
  {
    id: "d3",
    title: "Deal Memo - Lagos Fashion Week Runway",
    type: "Booking Confirmation",
    talentId: "1",
    talentName: "Zara",
    fileName: "deal_memo_lfw_runway_2026.pdf",
    uploadedAt: "2026-03-05",
    dateSigned: "2026-03-06",
    bookingId: "b1",
    isPersonalised: true,
  },
  {
    id: "d4",
    title: "Call Sheet - Lagos Fashion Week",
    type: "Call Sheet",
    talentId: null,
    talentName: "All (LFW)",
    fileName: "call_sheet_lfw_apr2026.pdf",
    uploadedAt: "2026-03-20",
    dateSigned: null,
    bookingId: "b1",
    isPersonalised: false,
  },
  {
    id: "d5",
    title: "Deal Memo - GTBank Commercial",
    type: "Booking Confirmation",
    talentId: "2",
    talentName: "Phoenix",
    fileName: "deal_memo_gtbank_2026.pdf",
    uploadedAt: "2026-03-12",
    dateSigned: "2026-03-13",
    bookingId: "b3",
    isPersonalised: true,
  },
  {
    id: "d6",
    title: "Payment Statement Q1 2026 - Atlas",
    type: "Financial",
    talentId: "3",
    talentName: "Atlas",
    fileName: "statement_atlas_q1_2026.pdf",
    uploadedAt: "2026-03-22",
    dateSigned: null,
    bookingId: null,
    isPersonalised: true,
  },
  {
    id: "d7",
    title: "Agency Policy Handbook",
    type: "Policy",
    talentId: null,
    talentName: "All Talent",
    fileName: "candor_policy_handbook_2026.pdf",
    uploadedAt: "2026-01-05",
    dateSigned: null,
    bookingId: null,
    isPersonalised: false,
  },
  {
    id: "d8",
    title: "Deal Memo - Ziva Lagos Editorial",
    type: "Booking Confirmation",
    talentId: "1",
    talentName: "Zara",
    fileName: "deal_memo_ziva_2026.pdf",
    uploadedAt: "2026-02-18",
    dateSigned: "2026-02-19",
    bookingId: "b2",
    isPersonalised: true,
  },
  {
    id: "d9",
    title: "Talent Agreement - Atlas",
    type: "Agreement",
    talentId: "3",
    talentName: "Atlas",
    fileName: "agreement_atlas_2025.pdf",
    uploadedAt: "2025-05-10",
    dateSigned: "2025-05-10",
    bookingId: null,
    isPersonalised: true,
  },
];

export const milestones = [
  {
    id: "m1",
    bookingId: "b1",
    talentId: "1",
    talentName: "Zara",
    bookingTitle: "Lagos Fashion Week - Runway",
    displayText: "Zara confirmed for Lagos Fashion Week runway show! Another milestone for the Candor family.",
    visibility: "named",
    approved: true,
    approvedAt: "2026-03-19T10:00:00",
    createdAt: "2026-03-18T15:00:00",
  },
  {
    id: "m2",
    bookingId: "b3",
    talentId: "3",
    talentName: "Atlas",
    bookingTitle: "GTBank - Commercial Campaign",
    displayText: "One of our talent just landed a major commercial campaign! Congratulations!",
    visibility: "anonymous",
    approved: true,
    approvedAt: "2026-03-12T14:00:00",
    createdAt: "2026-03-11T09:00:00",
  },
  {
    id: "m3",
    bookingId: "b1",
    talentId: "6",
    talentName: "Storm",
    bookingTitle: "Lagos Fashion Week - Runway",
    displayText: "Storm walks Lagos Fashion Week! Proud moment for the team.",
    visibility: "named",
    approved: false,
    approvedAt: null,
    createdAt: "2026-03-18T15:30:00",
  },
  {
    id: "m4",
    bookingId: "b1",
    talentId: "3",
    talentName: "Atlas",
    bookingTitle: "Lagos Fashion Week - Runway",
    displayText: "Atlas confirmed for Lagos Fashion Week! Keep soaring.",
    visibility: "named",
    approved: false,
    approvedAt: null,
    createdAt: "2026-03-18T16:00:00",
  },
];

export const openCastings = [
  {
    id: "oc1",
    title: "Editorial Shoot - Luxury Fashion",
    description: "Seeking female models for a high-end editorial spread. Must be comfortable with minimal styling and natural beauty looks.",
    brandName: "Vogue Afrique",
    category: "Fashion",
    location: "Lagos",
    shootDates: "2026-04-20 to 2026-04-21",
    workType: "Editorial",
    mediaUsage: "Print",
    requirements: "Female, 175cm+, size 6-8",
    deadline: "2026-04-10",
    status: "Open",
    interests: [
      { talentId: "1", talentName: "Zara", status: "interested", hasConflict: false, submittedAt: "2026-03-21T10:00:00" },
      { talentId: "3", talentName: "Atlas", status: "interested", hasConflict: true, submittedAt: "2026-03-21T11:00:00" },
    ],
    shortlisted: ["1"],
    selected: [],
    createdAt: "2026-03-20",
  },
  {
    id: "oc2",
    title: "TVC Campaign - Youth Energy",
    description: "Dynamic young talent needed for high-energy TVC. Looking for charismatic individuals with natural screen presence.",
    brandName: "Pepsi Nigeria",
    category: "Commercial",
    location: "Lagos",
    shootDates: "2026-05-01 to 2026-05-03",
    workType: "TVC",
    mediaUsage: "TV, Digital, Social",
    requirements: "Male or Female, 20-28 years, energetic",
    deadline: "2026-04-15",
    status: "Open",
    interests: [
      { talentId: "2", talentName: "Phoenix", status: "interested", hasConflict: false, submittedAt: "2026-03-22T09:00:00" },
    ],
    shortlisted: [],
    selected: [],
    createdAt: "2026-03-21",
  },
  {
    id: "oc3",
    title: "Runway - New Faces Showcase",
    description: "New and emerging talent showcase at Lagos Fashion Week. Great opportunity for new faces to gain runway experience.",
    brandName: "Lagos Fashion Week",
    category: "Fashion",
    location: "Lagos",
    shootDates: "2026-04-12",
    workType: "Runway",
    mediaUsage: "Social media, press",
    requirements: "New faces, all genders, 170cm+",
    deadline: "2026-04-01",
    status: "Open",
    interests: [
      { talentId: "5", talentName: "Velvet", status: "interested", hasConflict: false, submittedAt: "2026-03-22T14:00:00" },
      { talentId: "4", talentName: "Blaze", status: "interested", hasConflict: false, submittedAt: "2026-03-23T08:00:00" },
    ],
    shortlisted: ["5", "4"],
    selected: [],
    createdAt: "2026-03-18",
  },
  {
    id: "oc4",
    title: "Corporate Portraits - Annual Report",
    description: "Professional corporate headshots and lifestyle shots for banking annual report.",
    brandName: "GTBank",
    category: "Commercial",
    location: "Lagos",
    shootDates: "2026-04-05 to 2026-04-06",
    workType: "Commercial",
    mediaUsage: "Print, digital",
    requirements: "Male and Female, professional look",
    deadline: "2026-03-28",
    status: "Closed",
    interests: [
      { talentId: "2", talentName: "Phoenix", status: "selected", hasConflict: false, submittedAt: "2026-03-10T09:00:00" },
      { talentId: "3", talentName: "Atlas", status: "selected", hasConflict: false, submittedAt: "2026-03-10T10:00:00" },
      { talentId: "6", talentName: "Storm", status: "not_available", hasConflict: true, submittedAt: "2026-03-10T11:00:00" },
    ],
    shortlisted: ["2", "3", "6"],
    selected: ["2", "3"],
    createdAt: "2026-03-08",
  },
];

export const analyticsData = {
  bookingsByMonth: [
    { month: "Oct 2025", count: 3, revenue: 1200000 },
    { month: "Nov 2025", count: 5, revenue: 2100000 },
    { month: "Dec 2025", count: 2, revenue: 800000 },
    { month: "Jan 2026", count: 4, revenue: 1600000 },
    { month: "Feb 2026", count: 3, revenue: 1350000 },
    { month: "Mar 2026", count: 6, revenue: 3450000 },
  ],
  revenueByCategory: [
    { category: "Runway", revenue: 2150000, percentage: 32 },
    { category: "Editorial", revenue: 1350000, percentage: 20 },
    { category: "Commercial", revenue: 2000000, percentage: 30 },
    { category: "TVC", revenue: 1200000, percentage: 18 },
  ],
  revenueByClient: [
    { client: "Lagos Fashion Week", revenue: 2150000, bookings: 8 },
    { client: "GTBank", revenue: 1200000, bookings: 3 },
    { client: "Vogue Afrique", revenue: 900000, bookings: 4 },
    { client: "Ziva Lagos", revenue: 750000, bookings: 5 },
    { client: "Pepsi Nigeria", revenue: 0, bookings: 0 },
  ],
  talentPerformance: [
    { name: "Atlas", bookings: 15, revenue: 2800000, engagementRate: 92, selectionRate: 78 },
    { name: "Zara", bookings: 12, revenue: 2250000, engagementRate: 88, selectionRate: 75 },
    { name: "Phoenix", bookings: 8, revenue: 1600000, engagementRate: 85, selectionRate: 70 },
    { name: "Storm", bookings: 6, revenue: 1100000, engagementRate: 72, selectionRate: 60 },
    { name: "Muse", bookings: 3, revenue: 450000, engagementRate: 45, selectionRate: 33 },
  ],
  castingMetrics: {
    avgExpressionsPerCasting: 3.2,
    avgTimeToFill: "8 days",
    conversionRate: 67,
    totalCastings: 12,
    totalSelections: 8,
  },
  commissionEarned: {
    total: 870000,
    thisMonth: 360000,
    lastMonth: 270000,
    percentChange: 33,
  },
};

export const teamMembers = [
  {
    id: "u1",
    name: "Adaora Okeke",
    email: "adaora@candoragency.com",
    role: "ceo",
    status: "Active",
    joinDate: "2024-01-15",
    avatar: "AO",
  },
  {
    id: "u2",
    name: "Kemi Adeyemi",
    email: "kemi@candoragency.com",
    role: "md",
    status: "Active",
    joinDate: "2024-03-01",
    avatar: "KA",
  },
  {
    id: "u3",
    name: "Femi Johnson",
    email: "femi@candoragency.com",
    role: "booker",
    status: "Active",
    joinDate: "2025-01-10",
    avatar: "FJ",
  },
  {
    id: "u4",
    name: "Lola Bakare",
    email: "lola@candoragency.com",
    role: "booker",
    status: "Active",
    joinDate: "2025-06-01",
    avatar: "LB",
  },
];

export const systemSettings = {
  defaultCommissionRate: 20,
  escalationHours: 10,
  defaultPaymentTermsNew: "100% Upfront (48hrs before)",
  defaultPaymentTermsEstablished: "Net 14",
  defaultCastingDeadlineDays: 14,
  brandColour: "#00749E",
  contactEmail: "contact@candor-management.com",
};

export const recentActivity = [
  { id: 1, action: "New booking confirmed", detail: "Lagos Fashion Week - Runway show", time: "2 hours ago", type: "booking" },
  { id: 2, action: "Talent onboarding started", detail: "Adaeze Ikenna (Velvet) - Step 3 of 8", time: "5 hours ago", type: "talent" },
  { id: 3, action: "Invoice paid", detail: "INV-001 - Lagos Fashion Week - NGN 1,800,000", time: "1 day ago", type: "payment" },
  { id: 4, action: "Client inquiry received", detail: "Pepsi Nigeria - TVC Campaign", time: "1 day ago", type: "client" },
  { id: 5, action: "Casting shortlist sent", detail: "Vogue Afrique - Editorial shoot", time: "2 days ago", type: "casting" },
  { id: 6, action: "Invoice overdue", detail: "INV-002 - Ziva Lagos - NGN 450,000", time: "3 days ago", type: "alert" },
];

export const onboardingSteps = [
  "Application",
  "Screening",
  "Approval",
  "Offer Issued",
  "Contract Signed",
  "Orientation",
  "Profile Created",
  "Activated",
];
